# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

# Output File (CSV)
output_data_file = "output_data/cities.csv"

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities = pd.read_csv("output_data_file", encoding= 'unicode_escape')
cities.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Usinsk,65.99,57.53,-11.7,82,13,5.10,RU,1609562937
1,San Patricio,28.02,-97.52,53.6,66,75,8.05,US,1609562937
2,Puerto Carreño,6.19,-67.49,76.6,79,52,10.13,CO,1609562937
3,Heihe,50.24,127.49,-4.0,53,0,6.71,CN,1609562938
4,Bluff,-46.60,168.33,57.0,90,98,8.01,NZ,1609562938

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)

In [12]:
cities = cities.rename(columns={'City': 'City', ' Lat': 'Lat', ' Lng': 'Lng', 
                                ' Max Temp': 'Max Temp', ' Humidity': 'Humidity',
                                ' Cloudiness': 'Cloudiness', ' Wind Speed': 'Wind Speed',
                                ' Country': 'Country' , ' Date': 'Date'})
cities['Humidity'].max()

100

In [34]:
cities

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Usinsk,65.99,57.53,-11.70,82,13,5.10,RU,1609562937
1,San Patricio,28.02,-97.52,53.60,66,75,8.05,US,1609562937
2,Puerto Carreño,6.19,-67.49,76.60,79,52,10.13,CO,1609562937
3,Heihe,50.24,127.49,-4.00,53,0,6.71,CN,1609562938
4,Bluff,-46.60,168.33,57.00,90,98,8.01,NZ,1609562938
...,...,...,...,...,...,...,...,...,...
550,Chute-aux-Outardes,49.12,-68.40,14.00,78,90,3.36,CA,1609563077
551,Gaziantep,37.06,37.38,48.20,66,75,7.49,TR,1609563077
552,Kabalo,-6.05,26.92,68.79,97,100,1.45,CD,1609563078
553,Karratha,-20.74,116.85,96.49,41,2,16.75,AU,1609562825
554,Chapada dos Guimarães,-15.46,-55.75,82.40,65,0,8.05,BR,1609563078

In [21]:
locations= cities[["Lat", "Lng"]]
weights=cities['Humidity']

In [46]:
fig=gmaps.figure()

heatlayer=gmaps.heatmap_layer(
    locations,
    weights=weights,
    dissipating=False,
    max_intensity=100,
    point_radius=3
)
fig.add_layer(heatlayer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [35]:
perfect_site = pd.DataFrame(cities, columns = ["City", "Max Temp", "Wind Speed", "Cloudiness"])

max_temp = (perfect_site["Max Temp"] <= 90) & (perfect_site["Max Temp"] > 75)
wind_speed = perfect_site["Wind Speed"] < 5
cloudiness = perfect_site["Cloudiness"] >= 5

# new_types_df[max_temp & wind_speed & cloudiness]
perfect_site[max_temp & wind_speed & cloudiness]

                  City  Max Temp  Wind Speed  Cloudiness
43           Pemangkat     82.44        3.94          96
59                 Ifo     78.80        4.47          20
89              Nabire     86.58        4.45          92
102          Martapura     86.00        4.70          20
111        Kualakapuas     86.00        4.70          20
112               Juba     77.97        3.60          97
156  Benjamin Constant     75.20        2.24          40
157       Kudahuvadhoo     81.28        4.92          43
176               Biak     84.61        0.51          89
183          Sinnamary     77.41        2.53         100
194           Meulaboh     85.46        1.86          48
200    Arraial do Cabo     75.20        2.24          75
210            Cayenne     75.20        2.24          90
211               Auki     86.54        1.54          97
217             Touros     75.20        3.36          20
255              Minbu     80.74        4.72          17
270             Seddon     81.00        4.70          40
273            Kuching     86.00        2.24          40
286             Aitape     85.21        3.83          97
356         Tres Picos     75.88        2.82          98
378          Quelimane     78.80        2.24          40
379            Bintulu     86.00        2.24          20
384        Porto Velho     75.20        1.12          20
388            Kendari     87.44        3.98         100
415            Iquitos     75.20        3.36          75
423            Pitimbu     77.00        4.70          40
425          Manokwari     84.34        4.54         100
478       Sungai Penuh     78.71        1.72          96
505             Sorong     84.27        3.38         100
511          Sarangani     82.85        3.58          89
520           Galesong     84.20        4.70          40
523             Mumbai     80.60        1.10          20
537            Maumere     85.46        4.99          94

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [37]:

hotel = pd.DataFrame(cities, columns=["City", "Country", "Lat", "Lng"])

hotel["Hotel Name"] = ""
hotel

                      City Country    Lat     Lng Hotel Name
0                   Usinsk      RU  65.99   57.53
1             San Patricio      US  28.02  -97.52
2           Puerto Carreño      CO   6.19  -67.49
3                    Heihe      CN  50.24  127.49
4                    Bluff      NZ -46.60  168.33
..                     ...     ...    ...     ...        ...
550     Chute-aux-Outardes      CA  49.12  -68.40
551              Gaziantep      TR  37.06   37.38
552                 Kabalo      CD  -6.05   26.92
553               Karratha      AU -20.74  116.85
554  Chapada dos Guimarães      BR -15.46  -55.75

[555 rows x 5 columns]

In [39]:
target_coordinates = f"{hotel['Lat'][0]},{hotel['Lng'][0]}"
target_search = "hotel"
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

In [45]:
hotel_name = []

# params dictionary to update each iteration
params = {
    "radius": 500,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}

# taken from Airpost_Ratings Example done in class
for index, row in hotel.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))
    try:
       hotel_name.append(name_address['results'][0]['name'])
    except IndexError:
        hotel_name.append(np.nan)

hotel_name

['Gostinitsa "Uyutnyy Dom"',
 nan,
 'Casa Hotel Victoria',
 'Tianzhi Hotel',
 nan,
 'The Patagonian Lodge',
 'Falls Hotel',
 "Pension Maro'i",
 "Gina's Guesthouse - Upernavik",
 'Hotel Piesta',
 nan,
 nan,
 'Hostal Buenavista Patagonia',
 'Bell Aura Bed, Breakfast & Bistro',
 'Misty Waves Boutique Hotel',
 'Four Seasons Hotel Hong Kong',
 'Aongtong Homestay',
 'Mil 810 Ushuaia Hotel',
 'Hotel Loma Dorada',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Handan Hotel',
 'Esperance Central Accommodation',
 'Distinction Luxmore Hotel Te Anau',
 nan,
 nan,
 nan,
 'Hotel Coral Reef',
 'Hotel "Lenatur"',
 nan,
 'Bredasdorp Square',
 'Sails in the Desert',
 'Frobisher Inn',
 nan,
 'Hôtel Hiva Oa Hanakee Lodge',
 nan,
 'Murray Bridge Hotel',
 'Hotel Krystal Beach Acapulco',
 nan,
 'Cape Fox Lodge',
 nan,
 'Gorgeous George Hotel',
 nan,
 nan,
 nan,
 'Namibia Skipper services',
 nan,
 'End of The Road Ltd.',
 nan,
 'Hotel Grand Chancellor Hobart',
 'Domaine du Vacoa',
 'Posada Los Nonos',
 'Pousada do Diogo',
 'The Queens Hotel, Lerwick',
 'Ariya Hotel',
 '大新旅館',
 'Yamouri Inn',
 'HOTEL BOUTIQUE PALACIO ICO',
 nan,
 'DoubleTree by Hilton Jamestown',
 'Armenian Suite',
 'Dolphin Bay Hotel',
 nan,
 nan,
 'Aspen Suites Hotel Homer',
 nan,
 'King Eider Inn',
 nan,
 'Дом приезжих',
 'Stirling',
 'Azul Inn & Suites',
 nan,
 'garden lake villa',
 nan,
 nan,
 'Kodiak Compass Suites',
 'Hotel Tivoli',
 nan,
 nan,
 nan,
 'Villa Delisle, Hotel & Spa',
 nan,
 nan,
 nan,
 'Hotel Grand Papua Nabire',
 nan,
 'Lovers Point Inn',
 nan,
 'Villa das Meer',
 'The Red House',
 'ibis Styles Mt Isa Verona',
 nan,
 'Bikers Paradise',
 'Radisson Blu Polar Hotel, Spitsbergen',
 'Jacaré Palace Hotel',
 nan,
 nan,
 nan,
 'Mantra Nelson Bay',
 nan,
 nan,
 'Puffin Nest Capsule Hostel',
 'Sundog Inn',
 'Rekidhiye Inn',
 nan,
 'Hotel Patagonia',
 'Wisma Seroja',
 'Regency Hotel',
 nan,
 nan,
 'Hotel Açaí',
 nan,
 'Ecobank',
 nan,
 'Hotel Boutique Las Azucenas',
 'The Secret Garden Hotel',
 'Mehamn Arctic Hotel AS',
 'Days Inn & Suites by Wyndham Yellowknife',
 'Oyado Ekuhashi',
 'NUR',
 nan,
 'HOTEL SOVETSKAYA GAVAN',
 'The Sunflower Guesthouse',
 'Nítidos Aromas',
 'Hotel Castelo',
 nan,
 'Centre Formation En Informatique Les Jeunes',
 nan,
 nan,
 'Total - Numan Ferry Service Station',
 nan,
 'SpringHill Suites by Marriott Fairbanks',
 nan,
 nan,
 'Hotel Gervasoni',
 "Alexander's Hotel Hastings",
 nan,
 nan,
 nan,
 'Stensson',
 'Westenra Arms Hotel',
 nan,
 nan,
 'Hotel Lubango',
 'MyPond Hotel',
 'Sberbank Rossii',
 'Protea Hotel by Marriott Saldanha Bay',
 'Havelock Inn & Suites',
 nan,
 nan,
 nan,
 nan,
 'Dhaalu Inn Kudahuvadhoo by Atoll Hotels',
 'Hotel Libertador',
 'Turks Head Inne',
 'Grand Plaza Gulf Hotel',
 'Ivanhoe Village Caravan Resort',
 nan,
 nan,
 'Laura lodge',
 nan,
 'Beachfront Hotel Hokitika',
 'Saint-Augustin',
 nan,
 nan,
 nan,
 'Aurora Inn & Suites',
 nan,
 'Hotel Paoca',
 'Лазурит',
 'Descanso al Paso Chuy',
 nan,
 nan,
 'Hotel Kap Farvel',
 nan,
 nan,
 'Hotel Santa Maria',
 'Hotel Xaguate',
 nan,
 nan,
 nan,
 nan,
 'Hotel Edén La Palma',
 nan,
 'Château Arnaud',
 nan,
 nan,
 'Hôtel Le Grand Pavois',
 'WANGU RTV',
 'Hotel Meuligoe',
 nan,
 'TGP The Generics Pharmacy',
 'Sberbank Rossii',
 'Queens Hotel Cheltenham - MGallery',
 nan,
 'Hotel Pousada Caminho do Sol',
 nan,
 nan,
 'Glenwood Hot Springs Lodge',
 nan,
 'The Harbour Inn',
 'Hotel Mapuera',
 nan,
 nan,
 'Hotel Balai',
 'HOTEL KER ALBERTE',
 'Auki Lodge',
 'Gostinitsa Mechta',
 nan,
 nan,
 nan,
 'Fortuna Redwood Inn',
 nan,
 'Western Valley Inn',
 'גולדן טאוור הוטל בע"מ',
 nan,
 'Hotel Maison Joly',
 'Sitka Hotel',
 'Sberbank',
 'Byron Bay Hotel and Apartments - Boutique Accommodation',
 nan,
 'Hotel Hvide Falk',
 'La Cabaña Guainiana',
 'Hotel Klaksvík',
 'Red Lion Hotel & Conference Center St. George',
 nan,
 'Lorengau Harbourside Hotel',
 nan,
 nan,
 'Sberbank Rossii',
 'Skýjaborg apartments',
 'Arktika',
 'ibis Styles Port Macquarie',
 'Casa Rural Santa Lucía',
 'Port Lincoln YHA',
 "Maria's Hotel Nicte-Ha and Suites",
 nan,
 'Solenzo',
 'Naujaaraaluit – Clyde River Hotel',
 nan,
 'Hotel Chez Julot',
 'Chifeng Hotel',
 'Klover Hotel',
 'Hotel La Casa Del Algodon',
 'Hotel Santika Bengkulu',
 'Hotel de Turistas',
 'Hotel ICON, Autograph Collection',
 nan,
 'Hotel Dias',
 'Dolphin Hotel',
 nan,
 'Hotel Salinópolis',
 nan,
 'Havøysund Hotel & Rorbuer',
 'Four Points by Sheraton Juneau',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Hacienda Beach Club & Residences',
 nan,
 nan,
 'Sberbank Rossii',
 nan,
 'Oak Hotel',
 nan,
 'Serapi Hotel',
 nan,
 'Pousada Vivenda Oriente',
 nan,
 nan,
 nan,
 'Banco BIC - Agência Luau',
 'Apera Beach Front Bungalows',
 nan,
 nan,
 'Ulladulla Motel',
 'The Royal Hotel',
 "Tatiana's Hotel",
 nan,
 nan,
 "Vinha d'Areia Beach Hotel",
 'Villa Dolores Beach Resort',
 'Grant Hall Hotel',
 nan,
 'The Esplanade Hotel',
 nan,
 nan,
 'Super 8 by Wyndham Pierre SD',
 nan,
 nan,
 nan,
 'гостиница "Итуруп"',
 'Hondaafushi Island Resort',
 nan,
 'Residencial Roca',
 nan,
 'Auyuittuq Lodge (Inns North)',
 'A Snug Harbour Inn',
 'Residencial Prat',
 nan,
 nan,
 nan,
 nan,
 'Coral Sea Resort & Casino',
 'Desert Rose',
 'Hotel Amucan',
 'Chestnut-Manor Bed & Breakfast',
 'Super 8 by Wyndham Slave Lake AB',
 nan,
 nan,
 nan,
 'Hotel "Ternay"',
 'Morro do Sol Hotel e Eventos',
 nan,
 nan,
 'The Lakeview Inn',
 nan,
 nan,
 nan,
 'Kluane Green Sprout',
 'The Aaran Hotel',
 nan,
 nan,
 "L'Arpège Austral",
 nan,
 nan,
 'Fosshotel Húsavík',
 'Pousada Porto De Canoas',
 'Last Light Lodge',
 nan,
 nan,
 'Residence Dawha',
 'Sberbank',
 'Al Hasnan Cold Drink Santer',
 'Gostinitsa Grenada',
 nan,
 'Hilton Garden Inn Kutahya',
 nan,
 'Hotel Almendra',
 'Taloa Heights',
 nan,
 'Prospectors Inn Hotel',
 'Oumou Elghoura',
 nan,
 'Hanting Hotel',
 'Royal International Hotel',
 'Royal Hotel',
 'Hotel Lucia',
 nan,
 nan,
 'Mackay Oceanside Central Hotel',
 nan,
 nan,
 'Hotel Atlantico',
 'Livingstonia Lodges',
 'Hotel Boutique Ataraxy',
 nan,
 nan,
 nan,
 "Sip'n Save - Pastoral Hotel",
 'Crest Hotel',
 'Harbour View',
 nan,
 nan,
 'Hotel Cheval Blance',
 nan,
 'Hotel Bakkin',
 'Hotel Iberia de Coquimbo',
 nan,
 nan,
 'Hotel Flamingo',
 nan,
 nan,
 nan,
 'Hotel Apart',
 'Windvillage',
 'Oscar Hotel Executive',
 'Super 8 Hotel Longyan Bao Tai',
 nan,
 nan,
 nan,
 'Vestmanna guesthouse',
 nan,
 nan,
 nan,
 nan,
 'Best Western Thompson Hotel & Suites',
 nan,
 'Hotel Izala',
 nan,
 nan,
 'Motel Vanille',
 nan,
 nan,
 'Kavieng Niu Lodge',
 'Terråk Gjestegård',
 nan,
 nan,
 'Jalu Hotel',
 nan,
 'Hotel Santa Maria',
 'Regent Hotel - Dali',
 nan,
 nan,
 nan,
 nan,
 'Hotel Menel',
 'DoubleTree by Hilton Iquitos',
 nan,
 'Andrikken Hotel',
 'Katekero II',
 'Oceanside Motel',
 'Arman hotel',
 nan,
 'Auberge Treizéguy',
 nan,
 'The Nesbitt Arms',
 'hotel oriestom',
 'Skaslien Gjestgiveri',
 'Qinghai Hotel',
 'Country Pathfinder Motor Inn',
 'Hotel Kawissa Saurimo',
 nan,
 nan,
 'Laghetto Viverone Rio Grande',
 'Khamkor Biznes Tsentr',
 'The Columns Bed & Breakfast Inn',
 nan,
 nan,
 'Pousada Três Irmãos',
 'Balneario de Carballo',
 'Hotel Terrado Suites Antofagasta',
 'Vardø Hotel AS',
 nan,
 'LUXURY VILLA',
 'Hotel Barcelona',
 'hotêl doufoulougou',
 'Hotel Cabildo',
 "Billie's Backpackers Hostel",
 'Hotel Rissort',
 'Durrant House Hotel',
 'Argyll Hotel',
 nan,
 nan,
 "Gostinitsa Tsentral'naya",
 nan,
 nan,
 'Holiday Inn Express & Suites Pahrump',
 'Russelltown Inn',
 nan,
 'Hotel Rafa Cassilândia',
 'Angora Hotel',
 nan,
 nan,
 nan,
 "Krasnosel'kupnefteprodukt",
 'Jinjiang Inn Style Jiefang Road',
 nan,
 nan,
 'Nanjiang International Hotel',
 'Agence BNI Madagascar',
 'The Blue Guesthouse by Greenland Escape',
 'Fengyuan Hotel',
 nan,
 nan,
 nan,
 nan,
 'Gostinitsa Alrosa',
 nan,
 'Vytegra hotel',
 nan,
 nan,
 "The Old Salt Box Co. Skinner's House Burgeo",
 'Phu Cuong Hotel - Ca Mau',
 nan,
 'Hotel Prainha',
 nan,
 nan,
 'Edmar - Hotel Rooms and Restaurant',
 nan,
 nan,
 nan,
 'Friendship Hotel',
 'Vatica Beijing Changping District Changping Subway Station Xiguan Roundabout Hotel',
 nan,
 'Park Hotel Mount Gambier',
 'Central Palace Hotel - Castro (PR)',
 'Casa da Madrinha Graciosa',
 nan,
 'Ruyuan Inn',
 'Širvintos viešbutis, UAB',
 'visit Hotel',
 nan,
 'Hotel Helgeand Wisby',
 nan,
 'Uchi Lake Lodge',
 nan,
 'Hotel Mariat Sorong',
 'Itavale Hotel',
 'Hotel King Star',
 nan,
 'Astron Hotel',
 nan,
 nan,
 nan,
 'Naveen Hotel',
 'Hotel Buchanan Liberia',
 'Hôtel Alheri Maison Alheri',
 nan,
 'Lotte City Hotel Myeongdong',
 nan,
 'Hotel Jaciara',
 nan,
 nan,
 'Linhares Design Hotel',
 'Hotel Aroma',
 'Hotel Outeniqua George',
 nan,
 'Gostinitsa-Kafe "Komil\'fo"',
 'Super 8 by Wyndham Fallon',
 'Ballina Manor Boutique Hotel',
 nan,
 'Lakeview Inns & Suites - Fort Nelson',
 nan,
 'Sur Hotel',
 'BEST WESTERN Grand Hotel Elektra',
 'RE VITTORIO DE LUXE',
 'The Yankee Pedlar Inn',
 nan,
 'Merlin Hotel',
 'La Villa Hotel Restaurant Mollendo',
 nan,
 nan,
 'Katherine Motel',
 'Lotus Center Hotel',
 'sardar hotel',
 'Hotel Gold',
 nan,
 'OYO 1257 Hotel Sabang Hill',
 'Hotel R. Teresinha',
 'Khyber tobacco',
 nan,
 nan,
 'Gaziantep Şirehan Hotel',
 nan,
 nan,
 'Casa da Quineira']

In [47]:
hotel['Hotel Name']= hotel_name
hotel.dropna()
hotel.to_csv('hotel_export.csv')

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [48]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig
# Display figure

Figure(layout=FigureLayout(height='420px'))